<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class clinical_moh_333 extends Model
{
    protected $fillable= [
        'date',
        'anc_visits',
        'inpatient_no',
        'full_names',
        'age',
        'marital_status',
        'sub_location',
        'village',
        'parity',
        'gravidae',

        'lmp',
        'edd',
        'gestation_at_birth',
        'diagnosis',
        'date_of_delivery',
        'time_of_delivery',
        'duration_from_onset_of_labor',
        'mode_of_delivery',
        'apgar',
        'baby_life',
        'baby_weight',
        'sex_of_baby',
        'mothers_condition_after_delivery',
        'blood_loss',
        'placenta_complete',
        'counseled_and_tested_anc',
        'counseled_and_tested_mat',
        'hiv_status',
        'partners_for',
        'partner_status',
        'vdlr_serology_status',
        'arv_drud_given_mother',
        'arv_drud_given_baby',
        'vit_a_supplementation_mother',
        'food_options_baby',
        'delivery_conducted_by',
        'birth_notification',
        'date_of_discharge',
        'condition_of_baby_discharge',
        'comments',
        'no_with_aph',
        'no_with_pph',
        'no_with_eclampsia',
        'no_with_ruptured_uterus',
        'no_with_obstructed_labour',
        'no_with_sepsis',
        'no_with_aph_dead',
        'no_with_pph_dead',
        'no_with_eclampsia_dead',
        'no_with_ruptured_uterus_dead',
        'no_with_obstructed_labour_dead',
        'no_with_sepsis_dead',

        'no_of_normal_deliveries',
        'no_of_cesarean_sections',
        'no_of_breech_deliveries',
        'no_of_assisted_vaginal_deliveries',
        'total_live_births',
        'no_of_still_births',
        'no_of_underweight_babies',
        'no_of_preterm_babies',
        'no_of_discharged_alive',
        'no_of_referrals',
        'no_of_neonatal_deaths',
        'no_of_maternal_death',
        'no_counselled_of_hiv',
        'no_tested_with_hiv',
        'no_of_hiv',
        'no_issued_with_arvs',
        'no_of_infants_nevirapine',
        'no_of_deliveries_from_hiv_women',
        'no_initiated_cotrimoxaxole_women',
        'no_initiated_cotrimoxaxole_infants',
        'no_referred_follow_up_mothers',
        'no_referred_follow_up_partners',
        'department',
    ];
}
