<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class patient_file_orthopaedic_examination_form extends Model
{
    protected $fillable=['compalints','name','date','age','sex','height','weight','temp','pulse_rate','resp_rate','major_hand_r_or_l','blood_pressure_lying','standing','diagnosis','well_nourished','diabiliated','fair','disfigured','poor','obese','head_tilt_l_n_r','rotation_l_n_r','shoulder_tilt_l_n_r','rotation_l_n_r_1','hip_tilt_l_n_r','rotation_l_n_r_2','biceps_l','biceps_r','triceps_l','triceps_r','radial_l','radial_r','patellar_l','patellar_r','achelles_l','achelles_r','dejerines_dejerines_l','dejerines_dejerines_r','Bechtew_l','Bechtew_r','adisons_l','wrights_l','wrights_r','allens_l','allens_r','bdens_test_l','bdens_test_r','cervical_compressions_l','cervical_compressions_r','jacksons_compressions_l','jacksons_compressions_r','rotation_l_3','rotation_r_3','cervical_decompressions_l','cervical_decompressions_r','George_test_l','George_test_r','arc_of_abduction_l','arc_of_abduction_r','deltoid_extension_l','deltoid_extension_r','wrist_wrist_l','wrist_wrist_r','wrist_flexion_l','wrist_flexion_r','finger_cud_l','finger_cud_r','finger_spread_l','finger_spread_r','cold_hands_l','cold_hands_r','flexion_a','flexion_b','extension_a','extension_b','flexion_1_a','flexion_1_b','extension_1_a','extension_1_b','right_lateral_a','right_lateral_b','left_lateral_a','left_lateral_b','right_a','right_b','left_a','left_b','adams_sign_a','adams_sign_b','from_front_a','from_front_b','Dynamometer_grip_1a','Dynamometer_grip_1b','Dynamometer_grip_2a','Dynamometer_grip_2b','Dynamometer_grip_3a','Dynamometer_grip_3b','arms_1l','arms_1r','neck_1l','neck_1r','leg_1l','leg_1r','back_1l','back_1r','hypertensia','paresthia','positional','anesthia','hypesthesia','ROMBERG','finger_to_nose','toe_to_shin','finger_to_finger','kEMPS_r','kEMPS_l','TRENDELENBERG_r','TRENDELENBERG_l','LEWINS_test_r','LEWINS_test_l','MINORS_SIGN_r','MINORS_SIGN_l','NORMAL_a','NORMAL_b','IMPAIRED_a','IMPAIRED_b','PAIN_a','PAIN_b','NEED_ASSISTANCE','WALK_TOE','HEEL_WALK_r','HEEL_WALK_l','TOE_WALK_r','TOE_WALK_l','BABY_WALK'];
}
